// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQZXa82BJPmKmBoElEgeua5uQX9_TfD40',
    appId: '1:492173230323:android:c76060a700d88089787786',
    messagingSenderId: '492173230323',
    projectId: 'talkster-6440a',
    storageBucket: 'talkster-6440a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb8dIABzoV6XOiAUbi6WE_CrZGFBp9KMY',
    appId: '1:492173230323:ios:e5e91f53c0daac94787786',
    messagingSenderId: '492173230323',
    projectId: 'talkster-6440a',
    storageBucket: 'talkster-6440a.appspot.com',
    androidClientId: '492173230323-qg5bm62vl2eirgnng85qgp3sr19to52c.apps.googleusercontent.com',
    iosClientId: '492173230323-ccd9sa1n6f1dc7r71d7n4dmubm576q3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.talksterChattingApp',
  );
}
